baseURL = "https://SatoruItaya.github.io/portfolio"
languageCode = "en-us"
theme = "aafu"
publishDir = "docs"
canonifyurls = true

[params]
    title = "portfolio"
    author = "Darshan Baral"
    description = "Website title"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = true

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Satoru Itaya"
		location = "Tokyo, Japan"
        photo = "profile.jpeg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/satoru-itaya/"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/SatoruItaya"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/SItaya5"
            title = "Twitter"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "career"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "posts"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    # Experience section
    [params.career]
        title = "Career"
        icon = "fas fa-building"

        [[params.career.list]]
            position = "Engineer"
            dates = "2020.1 ~"
            link = "https://gunosy.co.jp/"
            company = "Gunosy Inc."
            details = "SRE Devision"
        [[params.career.list]]
            position = "Engineer, Consultant"
            dates = "2015.4 ~ 2019.12"
            link = "https://www.mizuho-ir.co.jp/index.html"
            company = "Mizuho Information & Reaearch Institute"
            details = "Markets Degital Technology Devision"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Master in Physics"
            college = "Tokyo University of Science"
            dates = "2013 - 2015"
            thesis_title = "Vortex solutions in a Witten-type model"
            thesis_link = "https://iopscience.iop.org/article/10.1088/1742-6596/563/1/012014"
        [[params.education.list]]
            degree = "Bachelor in Physics"
            college = "Tokyo University of Science"
            dates = "2009 - 2013"
 
    # Skill section
    [params.skill]
        title = "Skills"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "AWS"
        [[params.skill.list]]
            skill = "Kubernetes"
        [[params.skill.list]]
            skill = "Docker"
        [[params.skill.list]]
            skill = "Terraform"
        [[params.skill.list]]
            skill = "Python"
        [[params.skill.list]]
            skill = "Go"
    
    # Posts section
    [params.posts]
        title = "Posts"
        icon = "fas fa-sticky-note"

        [[params.posts.type]]
            type = "Gunosy Tech Blog"
            site_link = "https://tech.gunosy.io/"
            pages = [{ name = "Fitbitのカスタムレポートを作成してLINEに通知する", url = "https://tech.gunosy.io/entry/fitbit-activity-notifier" },
                     { name = "AWS Node Termination Handlerの新機能について", url = "https://tech.gunosy.io/entry/aws-node-termination-handler-new-feature" },
                     { name = "ECSのログ管理にFirelensを導入してみた", url = "https://tech.gunosy.io/entry/introducing-firelens" }]
            

        [[params.posts.type]]
            type = "Qiita"
            site_link = "https://qiita.com/str416yb"


    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-baseball-ball"
		
        [[params.hobby.list]]		
		    hobby = "Baseball"
        [[params.hobby.list]]		
		    hobby = "Soccer"
        [[params.hobby.list]]		
		    hobby = "Running"
        [[params.hobby.list]]
		    hobby = "Music"
        [[params.hobby.list]]
		    hobby = "Drinking"

